# Generated by Django 4.0.2 on 2022-02-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmany', '0002_alter_author_id_alter_authored_id_alter_book_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authors', models.ManyToManyField(to='bookmany.Author_2')),
            ],
        ),
        migrations.AddField(
            model_name='author_2',
            name='books',
            field=models.ManyToManyField(to='bookmany.Book_2'),
        ),
    ]
