# Generated by Django 4.0.2 on 2022-02-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmany', '0003_author_2_book_2_author_2_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_2',
            name='books',
            field=models.ManyToManyField(null=True, to='bookmany.Book_2'),
        ),
        migrations.AlterField(
            model_name='book_2',
            name='authors',
            field=models.ManyToManyField(null=True, to='bookmany.Author_2'),
        ),
    ]
