# Generated by Django 4.0.2 on 2022-02-20 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gview', '0002_alter_car_id_alter_cat_id_alter_dog_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ['id']},
        ),
    ]
