# Generated by Django 4.0.2 on 2022-02-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0002_album_artist_genre_track_album_artist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['title']},
        ),
    ]
