# Generated by Django 4.0.2 on 2022-02-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_alter_breed_id_alter_cat_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ['nickname']},
        ),
    ]
